source = ~/.config/hypr/conf/00-env.conf
source = ~/.config/hypr/conf/10-monitors.conf
source = ~/.config/hypr/conf/20-input.conf
source = ~/.config/hypr/conf/30-autostart.conf
source = ~/.config/hypr/conf/40-keybinds.conf
source = ~/.config/hypr/conf/50-rules.conf
source = ~/.config/hypr/conf/60-animations.conf
source = ~/.config/hypr/conf/90-theme.conf
source = ~/.config/hypr/conf/95-theme-auto.conf
