$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = ~/.config/quickshell/end4-lite/scripts/toggle-launcher.sh
$browser = firefox

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = MOZ_ENABLE_WAYLAND,1
env = WLR_NO_HARDWARE_CURSORS,1
env = SDL_VIDEODRIVER,wayland
env = SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS,0
env = GTK_ICON_THEME,Papirus
env = XDG_ICON_THEME,Papirus
