#!/usr/bin/env sh
set -eu

WALL_DIR="${HOME}/.config/wallpapers"
CURRENT_LINK="${WALL_DIR}/current"
COLORS_OUT="${HOME}/.config/hypr/conf/96-wallpaper-colors.conf"
SEARCH_DIRS="${WALL_DIR}
${HOME}/Pictures/Wallpapers
${HOME}/Pictures/wallpapers
${HOME}/Pictures
/usr/share/backgrounds
/usr/share/wallpapers"

list_wallpapers() {
    printf "%s\n" "${SEARCH_DIRS}" | while IFS= read -r dir; do
        [ -n "${dir}" ] || continue
        [ -d "${dir}" ] || continue
        find "${dir}" -maxdepth 3 -type f \
            \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \)
    done | sort -u
}

random_wallpaper() {
    list="$(list_wallpapers)"
    count="$(printf "%s\n" "${list}" | awk 'NF{c++} END{print c+0}')"
    [ "${count}" -gt 0 ] || return 1
    idx=$(( $(date +%s) % count + 1 ))
    printf "%s\n" "${list}" | sed -n "${idx}p"
}

normalize_hex() {
    printf "%s" "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^0-9a-f]//g' | cut -c1-6
}

darken_hex() {
    hex="$(normalize_hex "$1")"
    factor="${2:-0.55}"
    awk -v hex="${hex}" -v f="${factor}" 'BEGIN {
        r = strtonum("0x" substr(hex, 1, 2));
        g = strtonum("0x" substr(hex, 3, 2));
        b = strtonum("0x" substr(hex, 5, 2));
        r = int(r * f); g = int(g * f); b = int(b * f);
        if (r < 0) r = 0; if (r > 255) r = 255;
        if (g < 0) g = 0; if (g > 255) g = 255;
        if (b < 0) b = 0; if (b > 255) b = 255;
        printf "%02x%02x%02x\n", r, g, b;
    }'
}

write_colors_conf() {
    img="$1"
    c1="cba6f7"
    c2="89b4fa"

    if command -v magick >/dev/null 2>&1; then
        pair="$(magick "${img}" -resize 2x1\! -format '%[hex:p{0,0}] %[hex:p{1,0}]' info: 2>/dev/null || true)"
        p1="$(normalize_hex "$(printf "%s" "${pair}" | awk '{print $1}')")"
        p2="$(normalize_hex "$(printf "%s" "${pair}" | awk '{print $2}')")"
        if [ "${#p1}" -eq 6 ]; then
            c1="${p1}"
        fi
        if [ "${#p2}" -eq 6 ]; then
            c2="${p2}"
        fi
    fi

    inactive="$(darken_hex "${c1}" 0.55)"
    shadow="$(darken_hex "${c1}" 0.28)"

    cat > "${COLORS_OUT}" <<EOF
# Auto-generated by ~/.config/hypr/scripts/wallpaper-apply.sh
# Source: ${img}

general {
    col.active_border = rgba(${c1}ff) rgba(${c2}ff) 45deg
    col.inactive_border = rgba(${inactive}cc)
}

decoration {
    shadow {
        color = rgba(${shadow}88)
    }
}
EOF
}

apply_swww() {
    img="$1"
    command -v swww >/dev/null 2>&1 || return 1

    if ! pgrep -x swww-daemon >/dev/null 2>&1; then
        if command -v swww-daemon >/dev/null 2>&1; then
            nohup swww-daemon >/dev/null 2>&1 &
            sleep 0.25
        else
            swww init >/dev/null 2>&1 || true
        fi
    fi

    set -- grow center wipe
    idx=$(( $(date +%s) % 3 + 1 ))
    eval "transition=\${$idx}"
    angle=$(( $(date +%s) % 360 ))

    swww img "${img}" \
        --transition-type "${transition}" \
        --transition-angle "${angle}" \
        --transition-step 110 \
        --transition-fps 144 \
        --transition-duration 1.15 >/dev/null 2>&1
}

resolve_image() {
    choice="${1:-}"

    if [ -z "${choice}" ]; then
        if [ -f "${CURRENT_LINK}" ] || [ -L "${CURRENT_LINK}" ]; then
            printf "%s\n" "${CURRENT_LINK}"
            return 0
        fi
        random_wallpaper
        return $?
    fi

    if [ "${choice}" = "random" ]; then
        random_wallpaper
        return $?
    fi

    if [ -f "${choice}" ]; then
        printf "%s\n" "${choice}"
        return 0
    fi

    if [ -f "${WALL_DIR}/${choice}" ]; then
        printf "%s\n" "${WALL_DIR}/${choice}"
        return 0
    fi

    return 1
}

mkdir -p "${WALL_DIR}"

img="$(resolve_image "${1:-}" || true)"
[ -n "${img}" ] || {
    echo "No wallpaper found in configured directories." >&2
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl notify -1 3500 "rgb(ffaa66)" "Aucun fond d'ecran. Ajoute des images dans ~/.config/wallpapers ou ~/Pictures/Wallpapers." >/dev/null 2>&1 || true
    fi
    exit 1
}
[ -f "${img}" ] || {
    echo "Wallpaper not found: ${img}" >&2
    exit 1
}

ln -sfn "${img}" "${CURRENT_LINK}"
if ! apply_swww "${img}"; then
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl notify -1 3500 "rgb(ff6666)" "Impossible d'appliquer le fond: installe swww (sudo pacman -S swww)." >/dev/null 2>&1 || true
    fi
    exit 1
fi
write_colors_conf "${img}"

if command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
fi
